# Generated by Django 2.1.7 on 2019-03-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
